[metadata]
name = gh-unfollow
version = attr: src.__init__.__version__
description = Bulk unfollow GitHub users with smart rate limiting - clean up your following list fast
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
author = Uthuman & Co
author_email = dev@uthuman.com
url = https://github.com/uthumany/gh-unfollow

[options]
packages = find:
python_requires = >=3.8
install_requires =

[options.packages.find]
include = src*

[options.entry_points]
console_scripts =
    gh-unfollow = src.main:main
    github-unfollow = src.main:main
